# Generated by Django 4.1.2 on 2022-10-30 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todoTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 13, 49, 56, 546337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trashedtodo',
            name='todoTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 13, 49, 56, 547337, tzinfo=datetime.timezone.utc)),
        ),
    ]
