# Generated by Django 4.1.2 on 2022-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_todo_todotime_alter_trashedtodo_todotime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todoTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trashedtodo',
            name='todoTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
